server:
  port: 8888

spring:
  profiles:
    active: dev

catalpaFlat:
  param:
    valid:
      - classType: Integer
        beanPrefix: int
        beanName: intParamValidProcessor
      - classType: String
        beanPrefix: string
        beanName: stringParamValidProcessor
      - classType: String[]
        beanPrefix: array
        beanName: arrayParamValidProcessor